import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Oswald } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-oswald', // Definimos uma variável CSS
    weight: ['400', '700'],    // Escolha os pesos que vai usar
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="pt-BR" suppressHydrationWarning>
      <body
              className={`${oswald.variable} antialiased`}
      >
        {children}
              <Toaster
                  position="bottom-right"
                  richColors
                  closeButton
              />
      </body>
    </html>
  );
}
